### ISSUE TITLE
Adjust margins of articles to be more center screen than full width

### ISSUE THREAD

**Issue by ghost** [alexandrevicenzi/Flex#196]
Alex, great theme! I think it's one of the most popular ones so good job. I have a feature request which quite possibly may already be achievable but I'm no web developer hence why I'm asking.

When posting content I noticed it takes up the full width of the page which can make articles less inviting to read especially technical ones. For example, consider the beautiful hugo theme 
https://themes.gohugo.io//theme/beautifulhugo/post/markdown-syntax/

...it centers the content restricting it's width. Perhaps this could be a future feature or perhaps it's already achievable. In that case I would like to know how.

**Comment by alexandrevicenzi** [comment]
So, you want to look like this:

![image](https://user-images.githubusercontent.com/2637672/74138160-60b68f80-4bf1-11ea-9ee6-7a207626a54a.png)

Instead of this:

![image](https://user-images.githubusercontent.com/2637672/74138190-6d3ae800-4bf1-11ea-86cf-b0d18cc7e36f.png)

In the Hugo world, there's [Hyde](https://themes.gohugo.io//theme/hyde/post/markdown-syntax/) that's very similar to this theme.

I'm also [working on a new Hugo theme](https://github.com/alexandrevicenzi/lanyon) that will be a mix from Flex and Hyde.

**Comment by snehal2841** [comment]
Hey, I would like to do this.

**Comment by alexandrevicenzi** [comment]
@snehal2841 feel free to do so, best if there's a way to configure this in settings.

**Comment by snehal2841** [comment]
I have made the possible changes . Please review #252 . I hope it has became as you want it to be. As I am just from from the WebD background so I cannot assure that it has totally been corrected. But still please do check it out once.

**Comment by guqian110** [comment]
Hi, it seems the margins has been set to more center, I wonder if it's configurable and how can I change it to be full width, I didn't find any instruction about this in wiki. Thanks 😄

**Comment by alexandrevicenzi** [comment]
@guqian110 it's not configurable, you would need to override the CSS with a custom one to "fix" on your side.

Based on best practices for reading layouts, it makes more sense to limit it, otherwise a wide screen monitor will be unpleasant to read.

**Comment by guqian110** [comment]
@alexandrevicenzi thanks, it's more reasonable to limiting the width.
