### ISSUE TITLE
FAVICON property not in the documentation

### ISSUE THREAD

**Issue by angoca** [alexandrevicenzi/Flex#28]
I was reading the documentation, and I have not found documentation in the wiki about the favicon. Is this property only for flex?

**Comment by angoca** [comment]
The same happens for USE_LESS

**Comment by alexandrevicenzi** [comment]
Oh, it's missing :disappointed: 

Basically, `USE_LESS` will enable LESS instead of CSS. This is not good for production, only for development, it helps because you don't need to compile less files every time you make a change on it.

`FAVICON` is just a path for you favicon.ico. It could be an external file, or related url inside the "static" folder.

I'll update the Wiki with this info.

**Comment by alexandrevicenzi** [comment]
The docs are up to date now. Thanks.
