### ISSUE TITLE
Help with About Sections

### ISSUE THREAD

**Issue by dazajuandaniel** [alexandrevicenzi/Flex#64]
Hi Alexandre,
Great template, thank you for sharing!

I am having two issues with the about and contact sections I am trying to place.

1- Whenever I try to click on home or the image I get directed to http://dazajuandaniel.github.io/dazajuandaiel.github.io instead of http://dazajuandaniel.github.io

2- The about or contact section directs me to https://dazajuandaniel.github.io/dazajuandaniel.github.io/pages/about.html#about and the HTML file is corrupted.

Link to my repository:
[link](https://github.com/dazajuandaniel/dazajuandaniel.github.io)

I have two branches the "Master" and "Source". The "Source" contains all the pelican files. I am using Windows machine with the Git Bash.

**Comment by alexandrevicenzi** [comment]
Hi,

`SITEURL = 'dazajuandaniel.github.io'` should be `SITEURL = 'http[s]://dazajuandaniel.github.io'` or `SITEURL = '//dazajuandaniel.github.io'`

This is a trick with `href`, it will concat with the current URL if you don't put the schema.

The about page has the same issue, it can't find the CSS files because the link is broken.

**Comment by dazajuandaniel** [comment]
Thank you, it did the trick!
