### ISSUE TITLE
Question about changing css

### ISSUE THREAD

**Issue by richyvk** [alexandrevicenzi/Flex#70]
Hi

Could you help me out. I'm trying to edit your theme a bit - for example removing the lowercase text-transform for the sidebar items. I've removed it from the less and css files, then reinstalled the theme, but it doesn't seem to stop it happening.

How should I edit the css if not via the less or the minified css. I'm a newb on less and css and hwo they might work together.

Thanks

**Comment by alexandrevicenzi** [comment]
Hi,

If you change the LESS and compile it to CSS it should work. You just need to use your custom theme (set on pelican conf the right theme).

You can try enable `USE_LESS` to use LESS instead of CSS. This is a good way to know if the minified CSS isn't compiling.

You could also use `CUSTOM_CSS` setting to add your custom stuff.

**Comment by richyvk** [comment]
Awesome, thanks!

**Comment by peacej** [comment]
Sorry I've tried for hours and cannot get this to work.  What do you mean by "change the LESS" ? Which file specifically?  I just want the sidebar titles to not be converted to lowercase.
